//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 05:08:34 PM BST 
//


package de.dke.caex;

import Interfaces.ICAEXObject;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;


/**
 * 
 * 	CAEX basis object derived from CAEXBasicObject, augmented by
 * 	Name (required) and ID (optional).
 *       
 * 
 * <p>Java class for CAEXObject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CAEXObject"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.dke.de/CAEX}CAEXBasicObject"&gt;
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CAEXObject")
@XmlSeeAlso({
    de.dke.caex.CAEXFile.InstanceHierarchy.class,
    de.dke.caex.CAEXFile.InterfaceClassLib.class,
    de.dke.caex.CAEXFile.RoleClassLib.class,
    de.dke.caex.CAEXFile.SystemUnitClassLib.class,
    de.dke.caex.CAEXFile.AttributeTypeLib.class,
    SystemUnitClassType.InternalLink.class,
    SystemUnitClassType.class,
    RoleClassType.class,
    AttributeType.class,
    InterfaceClassType.class
})
public class CAEXObject
    extends CAEXBasicObject implements ICAEXObject
{

    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "Name", required = true)
    protected String name;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Override
	public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Override
	public void setName(String value) {
        this.name = value;
    }

}
