//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.1 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.04 at 05:08:34 PM BST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://www.dke.de/CAEX", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package de.dke.caex;
